language: emacs-lisp
sudo: false
env:
  - EMACS=emacs24
addons:
  apt:
    sources:
      - cassou-emacs
    packages:
      - emacs24
before_script:
  - $EMACS --version
script: make check emacs=$EMACS
